# Generated by Django 3.1.2 on 2021-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raeesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhai',
            name='coursetitleeight',
            field=models.CharField(default='SOFTWARE ENGEENIAR PRACTICAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitlefive',
            field=models.CharField(default='GRAPHICS', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitlefour',
            field=models.CharField(default='MATHEMATICS', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitlenine',
            field=models.CharField(default='MATHEMATICS PRACTICAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitleone',
            field=models.CharField(default='PYTHON', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitleseven',
            field=models.CharField(default='EMBEDED SYSTEM PRACTICAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitlesix',
            field=models.CharField(default='PYTHON PRACTICAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitleten',
            field=models.CharField(default='GRAPHICS PRACTICAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitlethree',
            field=models.CharField(default='SOFTWARE ENGEENIAR', max_length=40),
        ),
        migrations.AlterField(
            model_name='bhai',
            name='coursetitletwo',
            field=models.CharField(default='EMBEDED SYSTEM', max_length=40),
        ),
    ]
